var isoMap = new Map();
isoMap.set('Algeria', 'DZA');
isoMap.set('Argentina', 'ARG');
isoMap.set('Australia', 'AUS');
isoMap.set('Belgium', 'BEL');
isoMap.set('Bosnia and Herzegovina', 'BIH');
isoMap.set('Brazil', 'BRA');
isoMap.set('Cameroon', 'CMR');
isoMap.set('Chile', 'CHI');
isoMap.set('Colombia', 'COL');
isoMap.set('Costa Rica', 'CRI');
isoMap.set('Croatia', 'HRV');
isoMap.set('Ecuador', 'ECU');
isoMap.set('England', 'GBR');
isoMap.set('France', 'FRA');
isoMap.set('Germany', 'DEU');
isoMap.set('Ghana', 'GHA');
isoMap.set('Greece', 'GRC');
isoMap.set('Honduras', 'HND');
isoMap.set('Iran', 'IRN');
isoMap.set('Italy', 'ITA');
isoMap.set('Ivory Coast', 'CIV');
isoMap.set('Japan', 'JPN');
isoMap.set('Mexico', 'MEX');
isoMap.set('Netherlands', 'NLD');
isoMap.set('Nigeria', 'NGA');
isoMap.set('Portugal', 'PRT');
isoMap.set('Russia', 'RUS');
isoMap.set('South Korea', 'KOR');
isoMap.set('Spain', 'ESP');
isoMap.set('Switzerland', 'CHE');
isoMap.set('United States', 'USA');
isoMap.set('Uruguay', 'URY');
isoMap.set('Austria', 'AUT');
isoMap.set('Bulgaria', 'BGR');
isoMap.set('Canada', 'CAN');
isoMap.set('China PR', 'CHN');
isoMap.set('Denmark', 'DNK');
isoMap.set('Hungary', 'HUN');
isoMap.set('Israel', 'ISR');
isoMap.set('Norway', 'NOR');
isoMap.set('Paraguay', 'PRY');
isoMap.set('Qatar', 'QAT');
isoMap.set('Saudi Arabia', 'SAU');
isoMap.set('Scotland', 'GBR');
isoMap.set('South Africa', 'ZAF');
isoMap.set('Sweden', 'SWE');
isoMap.set('Tunisia', 'TUN');
isoMap.set('Turkey', 'TUR');
isoMap.set('Ukraine', 'UKR');
isoMap.set('United Arab Emirates', 'ARE');
isoMap.set('Kuwait', 'KWT');
isoMap.set('Wales', 'GBR');

exports.getMap = isoMap;